In [1]:
import numpy as np

In [2]:
a = 5
b = [12,24,48]
c = [[1,4,7],[2,5,8],[3,6,9]]

In [3]:
vector = np.array(b)

In [4]:
vector

array([12, 24, 48])

In [5]:
matrix = np.array(c)
matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [7]:
x = np.arange(0,10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.random.rand(5)

array([0.71096788, 0.15096825, 0.81599702, 0.81755534, 0.65473676])

In [12]:
np.random.rand(2,3)

array([[0.29299125, 0.01083007, 0.86589576],
       [0.09837854, 0.28280178, 0.1178953 ]])

In [13]:
# to display the random number in between 10 to 100
np.random.randint(10,100)

66

In [14]:
# give 20 different random values in between 10 to 100
np.random.randint(10,100,20)

array([61, 89, 95, 98, 58, 10, 74, 24, 14, 24, 64, 72, 14, 19, 95, 14, 15,
       98, 89, 36])

In [15]:
random_arr = np.random.randint(10,100,10)
random_arr

array([13, 60, 20, 38, 41, 29, 61, 16, 23, 25])

In [16]:
random_arr.reshape(2,5)

array([[13, 60, 20, 38, 41],
       [29, 61, 16, 23, 25]])

In [17]:
# shows the max number in list
random_arr.max()

61

In [18]:
# shows the min number in list
random_arr.min()

13

In [19]:
# shows the place of max number in list
random_arr.argmax()

6

In [20]:
# shows the place of min number in list
random_arr.argmin()

0

In [21]:
# creating an array in a range 0 - 50
arr_2d = np.arange(50)
arr_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [22]:
# reshaping an array in range 0-50 into rows & columns
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [23]:
# slicing 
arr_2d[2:4]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [24]:
# slicing in between row 2 to 4 & printing it after slicing 4 columns
arr_2d[2:4,4:]

array([[24, 25, 26, 27, 28, 29],
       [34, 35, 36, 37, 38, 39]])

In [25]:
arr = np.arange(0,15)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [27]:
# adding array
add = arr + arr

In [28]:
add

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [29]:
arr2 = np.arange(2,17)

In [30]:
arr2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [31]:
# adding arr + arr2
add = arr + arr2
add

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [32]:
# subtracting arr from arr2
sub = arr - arr2
sub

array([-2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2, -2])

In [33]:
# dividing arr/arr2
arr/arr2

array([0.        , 0.33333333, 0.5       , 0.6       , 0.66666667,
       0.71428571, 0.75      , 0.77777778, 0.8       , 0.81818182,
       0.83333333, 0.84615385, 0.85714286, 0.86666667, 0.875     ])

In [34]:
arr2/2

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. ])

In [35]:
np.log(arr2)

array([0.69314718, 1.09861229, 1.38629436, 1.60943791, 1.79175947,
       1.94591015, 2.07944154, 2.19722458, 2.30258509, 2.39789527,
       2.48490665, 2.56494936, 2.63905733, 2.7080502 , 2.77258872])

In [36]:
np.sqrt(arr2)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ])